# Generated by Django 4.2.4 on 2023-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0002_contactinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button1_url', models.URLField()),
                ('button2_url', models.URLField()),
            ],
        ),
    ]
