# Generated by Django 4.2.4 on 2023-08-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0003_carouselitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='button1_url',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='button2_url',
        ),
    ]
