# Generated by Django 4.2.4 on 2023-08-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0006_abouttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='job_logos')),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('company_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_website', models.URLField(blank=True)),
                ('resume', models.FileField(upload_to='resumes')),
                ('cover_letter', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
            ],
        ),
    ]
