# Generated by Django 4.2.4 on 2023-08-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0008_testimonial_remove_abouttext_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
